mypoll_chat/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('stream/', views.stream_chat, name='stream_chat'),
]

mypoll_chat/config/urls.py
from django.contrib import admin
from django.urls import path, include
from polls import views
urlpatterns = [
    
    path("", views.welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")), 
    path("account/", include("account.urls")),
    path('chat/', include('chat.urls')),
]

mypoll_chat/polls/urls.py
# polls/urls.py
# polls app에 대한 url-view 매핑파일 (URL Conf)

# URLConf  - urlpatterns =[ 매핑 설정 ]
# 매핑 설정 - path("url경로", View, name="설정식별이름") 함수를 이용

from django.urls import path
from . import views   # 상대 경로로 import. `.` 현재 모듈이 있는 패키지.

app_name = "polls" # 전체 설정에 대한 prefix(namespace). 
                   # 설정 name에 공통적으로 앞에 붙일 이름 ("app_name:name")

urlpatterns = [
    path("welcome", views.welcome, name="welcome"),
    path("vote_list", views.list, name="list"), # polls/list -> polls/vote_list
    path("vote_form/<int:question_id>", views.vote_form, name="vote_form"),
    path("vote", views.vote, name="vote"),
    path("vote_result/<int:question_id>", views.vote_result, name="vote_result"),
    path("vote_create", views.vote_create, name="vote_create"),
    path("vote_delete/<int:question_id>", views.vote_delete, name="vote_delete"),
]


# polls/vote_form/<path파라미터값 타입:view의 파라미터변수명>
# <int:   #path parameter값을 int로 전달해라.
# <   :question_id> # view의 question_id 변수로 전달해라.
# type: int, str

mypoll_chat/polls/models.py
# polls/models.py
#  모델 클래스들을 정의
from django.db import models

# 모델 클래스 정의 - Question(설문질문) - Choice(설문의 보기)
## 1. models.Model을 상속
## 2. class 변수로 Field들을 정의: 
#                     Field == DB column, Model객체의 Instance 변수 이 둘에 대한 설정

# Model class 정의 할 때 primary key Field를 선언하지 않으면, 
# id (int auto_increment) 컬럼이 primary key 컬럼으로 자동으로 생성된다.
class Question(models.Model):
    # Field 정의: 변수명-(instance변수명, column 이름)
    #             Field 객체를 할당. Field객체 - column 설정(type, null허용여부,..)
    question_text = models.CharField(max_length=200)  #CharField() -> 문자열타입(varchar, str)
    pub_date = models.DateTimeField(auto_now_add=True) 
    # DateTimeField: 일시타입(datetime, datetime.datetime)
    # auto_now_add: insert 될 때 일시를 자동 입력.
    
    
    def __str__(self):
        return f"{self.id}. {self.question_text}"

    # create table question(
    #     question_text varchar(200),
    #     pub_date datetime current_timestamp
    # )

# 보기 테이블
class Choice(models.Model):

    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0) # 정수타입 (int, int)
    question = models.ForeignKey(
        Question, # 참조할 Model Class
        on_delete=models.CASCADE # 참조 값이 삭제 된 경우 어떻게 할지 -> cascade: 삭제
        # , related_name="my_choice" # q.my_choice.all()
    ) # FK -> Question의 id를 참조.

    def __str__(self):
        return f"{self.id}. {self.choice_text}"

# create table choice(
#     choice_text varchar(200) not null,
#     votes int not null default 0,
#     question int,
#     constraint q_fk foreign key (question) references QUESTION(id) on delete cascade
# )


# 모델 클래스 정의 한 후에 Database에 적용
# Project Root >   python manage.py makemigrations         # 모든 app들에 적용
#                  python manage.py makemigrations  polls  # polls app에 만 적용
#     -> table에 적용(생성, 수정) 할 코드를 작성.

#  python manage.py migrate  # DB에 적용(table생성, 수정)

# python  manage.py  inspectdb > a.py

mypoll_chat/polls/forms.py
# polls/forms.py

from django import forms

# Form 클래스를 정의 - forms.Form 을 상속
## Form 클래스: 입력 폼들을 모아서 정의한 클래스
##   - Form Field: 개별 입력 폼(input) 들을 정의 
##                 클래스 변수로 정의. 입력폼 양식-파이썬 타입 관련되어 FormField객체를 할당.

# 설문 질문 등록 폼 
class QuestionForm(forms.Form):
    # Form Field -> 질문 입력
    # 변수명 (요청파라미터 name) = FormField(): 어떤 값을 입력받을지 타입.

    # Form Field 1개 -> 한 개 이름의 요청파라미터 입력 태그를 설정.
    ## 같은 이름으로 여려개 입력을 받을 경우 -> Form set을 이용해서 구현.
    question_text = forms.CharField( # 문자열 입력 폼 - View에서 문자열로 읽기.
        label="", # 입력에 대한 label을 설정.
        max_length=200, # 최대 입력 글자수.
        required=True, # 필수 입력인지 여부
        widget=forms.TextInput(             # widget은 input 태그를 지정. type=text
            attrs={"class":"form-control"}  # 입력 tag의 attribute 설정.
        )
    )
        # 검증 메소드를 추가. -> 업무규칙의의한 검증
        # 메소드 이름 규칙: 1. 개별 Field들을 검증 - clean_필드명
        #                  2. 전체 입력 데이터들을 검증 - clean
        # 검증 메소드는 기본 검증을 하고 나서 호출한다.
        # - 구현: 검증 통과-return 요청파라미터값. 검증오류: raise ValidationError
    def clean_question_text(self):
        txt = self.cleaned_data['question_text'].strip() # 기본 검증을 통과한 입력값.
        # 질문은 5글자 이상 가능.
        if len(txt) < 5:
            raise forms.ValidationError("질문은 5글자 이상 입력하세요.")
        return txt
    
    
class ChoiceForm(forms.Form):
    choice_text = forms.CharField(
        label="", # Labal을 생성하지 않게 한다.
        max_length=200,
        required=True,
        widget=forms.TextInput(attrs={"class":"form-control"})
    )
    # def clean_choice_text(self):
    #     txt = self.cleaned_data['choice_text'].strip() # 기본 검증을 통과한 입력값.
    #     # 질문은 1글자 이상 가능.
    #     if len(txt) < 2:
    #         raise forms.ValidationError("보기는 2글자 이상 입력하세요.")
        
    #     return txt
    
    


# ChoiceForm을 이용해서 FormSet 클래스를 생성
# FormSet : Form + Set: Form들의 집합
#           Form클래스의 내용을 중복해서 가지는 class
#           같은 이름으로 여러개의 입력을 받아야 할 때.
#           특정 input 양식을 반복적으로 여러개 가지는 입력 페이지를 구성할 때.
ChoiceFormSet = forms.formset_factory(
    ChoiceForm, # Form클래스
    extra=2,    # Form을 몇개 (반복해서) 만들지 개수
)

mypoll_chat/polls/views.py
# polls/views.py

from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse 
# url conf의 설정 이름으로 url을 조회하는 함수
## path("url", view함수, name='name')
# reverse("name") => url

from django.db import transaction  # DB Transaction 처리.
from django.core.paginator import Paginator

from datetime import datetime
from .models import Question, Choice

# Create your views here.

# 설문 welcome page view
#  요청 -> 인삿말 화면을 응답.
def welcome(request):
    print("welcome 실행")
    # 요청 처리
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # 응답 화면 생성 -> template 호출(template이 사용할 값을 전달-now)
    response = render( # template 호출 -결과-> HttpResponse로 반환
        request, # HttpRequest
        "polls/welcome.html", # 호출할 template의 경로
        {"now":now} # template에 전달할 값들. name-value 전달.
                    # Context Value 라고 한다.
    )
    print(type(response)) # server를 실행한 터미널에 출력.
    return response

def welcome_old(request):
    print("welcome 실행")
    # 요청 처리
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    # 처리결과 페이지 생성 -> html을 str로 구현.
    res_html = f"""<!doctype html>
<html>
    <head>
        <title>설문 main</title>
    </head>
    <body>
        <h1>Welcome</h1>
        <p>저희 설문 페이지를 방문해 주셔서 감사합니다.</p>
        현재 시간: {now}
    </body>
</html>
"""
    res = HttpResponse(res_html)
    return res 


# 설문(질문) 목록 조회
## 전체 question들을 조회해서 목록 html을 반환.
## 요청 url: polls/list
## view함수: list
## template: polls/list.html
#########################################
# 페이징 처리 안한 list 함수
#########################################
def list_old(request):
    # 1. DB에서 질문 목록 조회 -> Model 사용
    question_list = Question.objects.all().order_by("-pub_date")
    # 2. 응답 페이지를 생성(template 사용) -> 반환
    return render(
        request, 
        "polls/list.html", 
        {"question_list":question_list}
    )

#########################################
# Paging 처리 list
#
# - template 호출 전달할 Context Value
#    - 현재 페이지의 데이터 - Page객체
#    - 현재 페이지가 속한 페이지 그룹의 페이지번호 start/end index
#    - 현재 페이지 그룹의 시작 페이지가 이전 페이지가 있는지 여부,  있다면 이전 페이지 번호
#    - 현재 페이지 그룹의 끝 페이지가 다음 페이지가 있는지 여부,  있다면 다음 페이지 번호
def list(request):
    paginate_by = 10      # 한 페이지당 데이터 개수
    page_group_count = 10 # 페이지 그룹당 페이지 수
    # http://ip:port/polls/list?page=16
    current_page = int(request.GET.get("page", 1)) # 현재 조회 요청이 들어온 페이지 번호. GET방식의 요청파라미터

    # Paginator
    q_list = Question.objects.all().order_by("-pk")
    pn = Paginator(q_list, paginate_by)

    # 현재 페이지가 속한 PageGroup의 시작 페이지의 index, 종료 페이지의 index
    start_index = int((current_page - 1) / page_group_count) * page_group_count
    end_index = start_index + page_group_count

    page_range = pn.page_range[start_index : end_index] # 시작 ~ 끝 페이지 번호 조회

    # template에 전달할 context value dictionary
    context_value = {
        "page_range": page_range,
        "question_list": pn.page(current_page) # Page[Question]
    }

    # PageGroup의 시작페이지가 이전페이지가 있는지 여부, 이전 페이지 번호
    # PageGroup의 마지막페이지가 다음 페이지가 있는지 여부, 다음 페이지 번호

    start_page = pn.page(page_range[0]) # 시작 페이지 Page객체
    end_page = pn.page(page_range[-1])  # 마지막 페이지 Page객체

    if start_page.has_previous():
        context_value['has_previous'] = start_page.has_previous()
        context_value["previous_page_number"] = start_page.previous_page_number()

    if end_page.has_next():
        context_value['has_next'] = end_page.has_next()
        context_value['next_page_number'] = end_page.next_page_number()

    # 응답 template 호출
    return render(
        request,
        "polls/list.html",
        context_value
    )



# 개별 설문을 할 수 있는 페이지(설문폼)로 이동.
## 질문 id를 path parameter로 받아서 
##    그 질문과 보기를 DB조회해서 화면에 출력 - 설문 입력 폼
### path parameter: http://ip:port/path1/path2/path3/전달값1/전달값2
### request(요청) parameter: 
#          http://ip:port/path1/path2/path3?name=전달값1&name=전달값2

# 요청URL: /polls/vote_form/질문ID
# view함수: vote_form
# template: 정상 - polls/vote_form.html
#            오류 - polls/error.html
def vote_form(request, question_id):
    # question_id 파라미터 - path parameter 값을 받을 변수.
    # view함수의 두번째 파라미터부터는 path parameter를 받을 변수들. 
    ## 파라미터 변수명은 urls.py에 등록한 변수명으로 선언하면된다.
    
    # 1. DB에서 question_id로 질문을 조회
    try:
        question = Question.objects.get(pk=question_id)
        # 응답 화면 요청
        return render(
            request,
            "polls/vote_form.html",
            {"question":question}
        )

    except:
        # print(f"{question_id}의 질문이 없습니다.")
        return render(
            request,
            "error.html",
            {"error_message":f"요청하신 {question_id}번 질문이 없습니다."}
        )


# 설문 처리 하기.
## 선택한 보기(Choice)의 votes를 1 증가. 투표 결과를 보여주는 페이지로 이동.

# 요청URL: polls/vote
# view함수: vote
# 응답:  정상 - polls/vote_result.html
#        오류 - polls/vote_form.html

# form입력 -> 요청파라미터로 읽는다.
# 요청파라미터: GET - request.GET -> dictionary {"요청파라미터이름":"요청파라미터값"}
#             POST - request.POST -> dictionary 
def vote(request):
    # 요청파라미터 조회
    choice_id = request.POST.get('choice') # 선택된 보기의 ID
    question_id = request.POST.get('question_id') # 질문 ID

    ##########################################
    # 쿠키(Cookie)를 이용해서 현재 사용자가 이미 투표한 적이 있는 질문이면 투표를 못하게 한다.
    #    - 쿠키 예제 연습 (실제는 DB를 이용해서 처리. 사용자-투표질문번호 테이블이용.)
    # -  쿠키에 voted_question 에 요청한 question_id가 있는지 여부 확인
    #    - 있으면 error_message 와 함께 투표못한다고 vote_form으로 이동
    #    - 없으면 투표 처리. -> cookie voted_question에 투표 질문 ID를 추가.
    ##########################################
    voted_question_ids = request.COOKIES.get('voted_question') #"1,7,10"
    print(voted_question_ids)
    if voted_question_ids:
        q_id_list = voted_question_ids.split(",") #["1", "7", "10"]
        if question_id in q_id_list: # 이미  투표한 질문
            question = Question.objects.get(pk=question_id)
            return render(request, "polls/vote_form.html",
                         {"question":question, "error_message":"이미 투표한 질문입니다."})

    # choice_id가 넘어왔다면 choice의 votes를 1 증가
    if choice_id != None:
        selected_choice = Choice.objects.get(pk=choice_id)
        selected_choice.votes += 1
        selected_choice.save()     # update

        ######################################
        # voted_question Cookie에 투표한 질문_ID 추가

        voted_question_ids = str(question_id) if not voted_question_ids else f"{voted_question_ids},{question_id}"        

        # TODO: 업데이트 결과를 보여주는 View(vote_result)를 redirect방식으로 요청
        # urls.py에 path에 등록된 이름으로 url을 조회
        ## app_name:설정이름
        ## path parameter있는 경우 args=[path parameter값, ..]
        url = reverse("polls:vote_result", args=[question_id])
        print(type(url), url)
        response = redirect(url)
        response.set_cookie("voted_question", voted_question_ids)
        return response

        # # 결과페이지 - question 조회
        # question = Question.objects.get(pk=question_id)
        # return render(
        #     request, "polls/vote_result.html", {"question":question}
        # )
    else: # choice를 선택하지 않고 요청한 경우.
        question = Question.objects.get(pk=question_id)
        return render(
            request,
            "polls/vote_form.html",
            {"question":question, "error_message":"보기를 선택하세요."}
        )
    

# 개별 질문의 투표 결과를 보여주는 View
# 요청 URL: /polls/vote_result/<question_id>
# View함수: vote_result
# 응답: polls/vote_result.html
def vote_result(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(
        request, "polls/vote_result.html", {"question":question}
    )


# 설문(질문)을 등록 처리.
# 요청 URL: /polls/vote_create
# View 함수: vote_create
#    - HTTP 요청 방식에 따라 입력양식을 제공할지, 처리할지 결정.
#      - GET: 입력양식을 제공 (설문문제와 보기를 입력할 수있는 화면)
#      - POST: 등록처리
# 응답: - GET 처리: (template) polls/vote_create.html
#       - POST처리: redirect 방식응답 ==> list View를 요청.
# Http 요청방식 조회 - request.method (str: "GET", "POST")
def vote_create_old(request):
    http_method = request.method
    if http_method == "GET":
        # 입력폼 제공
        return render(request, "polls/vote_create.html")

    elif http_method == "POST":
        # 등록 처리
        # 1. 요청(Path)파라미터 읽기.
        # 2. 요청파라미터 검증. - 성공->처리, 실패->입력폼페이지(에러)를 응답
        # 3. 업무 처리 -> DB작업
        # 4. 응답.
        
        # 요청파라미터 조회 - request.POST(GET) => dictionary구현체
        ### 요청파라미터 중 question_text를 조회
        question_text = request.POST.get("question_text") # str반환.
        ### 요청파라미터 중 choice_text를 조회 (같은 이름으로 여러개 전달)
        ####  choice_text=보기1&choice_text=보기2&..
        choice_list = request.POST.getlist("choice_text") # list[str]
        # ["보기1","보기2", ]
        # 요청파라미터 검증 (질문: 1글자 이상, 보기: 2개이상 각각 1글자 이상.)
        if not question_text.strip(): # 빈문자열일 경우
            return render(
                request, "polls/vote_create.html",
                {"error_msg":"문제를 한 글자 이상 입력하세요.",
                 "question_text": question_text, 
                 "choice_list":choice_list}
            )
        
        ## 보기검증. choice_text가 넘어온게 없거나
        ##         (choice_text가 넘어온게 있는데 값이 있는 것이 2개가 안되면) ==> 검증 실패
        if not choice_list or (choice_list and len([c for c in choice_list if c.strip()]) < 2):
            return render(
                request, "polls/vote_create.html",
                {"error_msg":"보기는 두개 이상 입력해야 합니다.",
                 "question_text": question_text, 
                 "choice_list":choice_list}
            )
        try:
            # with block을 정상적으로 처리하면 commit 실행
            # with block 실행 중 Exception이 발생하면 rollback 
            #                                     (Insert작업 처음 상태로 돌린다.)
            with transaction.atomic(): # Transaction 시작
                # 검증 통과 -> DB에 저장.(Insert)
                #  모델.save()
                q = Question(question_text=question_text) #id/pub_date 자동입력.
                q.save()
                
                # raise Exception("문제가 발생했습니다.")

                for c in choice_list:
                    choice = Choice(choice_text=c, question=q) # id/vote 는 자동입력

mypoll_chat/polls/templates/polls/error.html
<!-- templates/polls/error.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>에러</title>
</head>
<body>
    <a href="/polls/welcome">설문 홈</a>
    <p>
        요청하신 것을 처리하지 못했습니다.<br>
        에러메세지: {{error_message}}
    </p>
</body>
</html>

mypoll_chat/polls/templates/polls/list.html
<!-- 'layout/main_layout.html' 레이아웃을 여기로 불러와라. -->
{% extends 'layout/main_layout.html' %}

<!-- main_layout.html의 block에 넣을 내용들만 정의 -->
{% block title %}설문 목록{% endblock title %}
{% block contents %}
<h1>설문목록</h1>
<ul class="list-group">
    <!-- 반복문 - 
       question_list(context_value:QuerySet)의 Question들을 출력 -->
    {% for question in  question_list %}
        <li class="list-group-item list-group-item-action">
            <!-- /polls/vote_form/{{question.pk}} -->
            <a href="{% url 'polls:vote_form' question.pk %}" class="btn">
                {{question.pk}}. {{question.question_text|truncatewords:10}}
                {#- 글자수: {{question.question_text|length}} - {{question.pub_date|date:'Y-m-d'}}#}
            </a> 
            {% if user.is_authenticated %}
                <a href="{% url 'polls:vote_delete' question.pk %}" class="btn btn-danger btn-sm">
                    질문 삭제
                </a>
            {% endif %}
        </li>
    {% empty %}
        {# 처음 부터 question_list가 비어있으면#}
        <b>아직 등록된 질문이 없습니다.</b>
    {% endfor %}
</ul>

<!-- 페이징 처리 - 페이지 링크들 출력 -->
<ul id="page_group" class="pagination mt-3">
    {# 이전 페이지 그룹으로 이동하는 버튼 #}
    {% if has_previous %}
        <li class="page-item">
            <a href="{% url 'polls:list' %}?page={{previous_page_number}}" class="page-link">
                이전
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">이전</span>
        </li>
    {% endif %}

    {# 현재 페이지그룹의 페이지로 이동하는 링크 - 현재 페이지는 링크를 걸지 않는다.#}
    
    {% for page_no in page_range %}
        {% if question_list.number == page_no %}
            <li class="page-item active">
                <span class="page-link">{{page_no}}</span>
            </li>
        {% else %}
            <li class="page-item">
                <a href="{% url 'polls:list' %}?page={{page_no}}" class="page-link">{{page_no}}</a>
            </li>
        {% endif %}
    {% endfor %}
    
    {# 다음 페이지 그룹으로 이동하는 버튼 #}
    {% if has_next %}
        <li class="page-item">
            <a href="{% url 'polls:list' %}?page={{next_page_number}}" class="page-link">
                다음
            </a>
        </li>
    {% else %}
        <li class="page-item disabled">
            <span class="page-link">다음</span>
        </li>
    {% endif %}
</ul>
{% endblock contents %}

mypoll_chat/polls/templates/polls/vote_create.html
{% extends "layout/main_layout.html" %}
{% block title%}설문 등록 {% endblock title %}
{% block contents %}
    <h1>설문 문제 등록</h1>
    {% if error_msg %}
        <div style="color:red">{{error_msg}}</div>
    {% endif %}
    <form method="post">
        {% csrf_token %}
        <h3>질문</h3>
        <input type="text" name="question_text" class="form-control" value="{{question_text}}" required>
        
        <h3>보기</h3>
        <div id="choice_layer">
            {% if not choice_list %}
                <div>
                    <input type="text" name="choice_text" class="form-control" required>
                </div>
                <div><input type="text" name="choice_text" class="form-control"  required></div>
            {% else %} <!-- choice_list = ["보기1", "보기2"]-->
                {% for choice in choice_list %}
                    <div>
                        <input type="text" 
                               name="choice_text" 
                               class="form-control" 
                               value="{{choice}}"  required>
                    </div>
                {% endfor %}
            {% endif %}

        </div>
        <div id="btn_layer">
            <button type="button" onclick="addChoice()" class="btn btn-info">보기추가</button>
            <button type="button" onclick="delChoice()" class="btn btn-info">보기삭제</button>
            <button type="submit" class="btn btn-primary">문제 등록</button>
        </div>
    </form>
{% endblock contents %}
{% block javascript %}
<script>
    function addChoice() {
        // <input type="text" name="choice_text" size="100"><br> 추가
        const input = document.createElement("input");
        input.setAttribute("type", "text");
        input.setAttribute("name", "choice_text");
        input.setAttribute("class", "form-control");
        input.setAttribute("required", true);
        // const br = document.createElement("br");
        
        //input + br을 묶을 div 생성
        const div = document.createElement("div");
        div.appendChild(input);
        // div.appendChild(br);

        // 추가할 choice_layer 를 조회
        const layer = document.querySelector("#choice_layer");
        layer.appendChild(div);
    }
    function delChoice() {
        // #choice_layer에서 보기 입력폼을 하나 삭제
        // 보기 입력이 두개이면 삭제 하지 않는다. (최소 두개는 유지)
        // 삭제: 부모노드.removeChild("삭제할 노드")
        const layer = document.querySelector("#choice_layer");
        if (layer.children.length > 2) {
            // 삭제
            layer.removeChild(layer.lastChild);
        }else{
            //유지
            alert("보기가 두개이면 삭제가 안됩니다.");;            }
    }
</script>
{% endblock javascript%}

mypoll_chat/polls/templates/polls/vote_create_form.html
<!-- polls/templates/polls/vote_create_form.html -->
{% extends "layout/main_layout.html"%}

{% load static %}

{%block title%}질문 등록 - form.py{%endblock title%}
{%block contents%}

<h1>설문 문제 등록 -  forms.py 이용</h1>

<form method="post">
    {% csrf_token %}

    <h3>질문</h3>
    {{q_form}}

    <h3 class="mt-2">보기</h3>

    {{ c_formset.management_form }}
    {% comment %}
         <input type="hidden" name="form-TOTAL_FORMS" value="2" id="id_form-TOTAL_FORMS">
         <input type="hidden" name="form-INITIAL_FORMS" value="0" id="id_form-INITIAL_FORMS">
         <input type="hidden" name="form-MIN_NUM_FORMS" value="0" id="id_form-MIN_NUM_FORMS">
         <input type="hidden" name="form-MAX_NUM_FORMS" value="1000" id="id_form-MAX_NUM_FORMS">
        formset객체의 정보
        이 정보들을 view에 전달해야 정상적으로 처리가 가능.
        TOTAL_FORMS: formset으로 생성한 input들의 개수. view에서는 이 개수만큼만 읽어서 처리
                  그래서 동적으로 input을 생성/삭제할 경우 TOTAL_FORMS의 값을 변경해야 한다.
    {% endcomment %}
    <div id="choice_layer">
        {% for c_form in c_formset %}
            {{c_form}}
        {% endfor %}
    </div>
    <div id="btn_layer">
        <button type="button" onclick="addChoice()" class="btn btn-info">보기추가</button>
        <button type="button" onclick="delChoice()" class="btn btn-info">보기삭제</button>
        <button type="submit" class="btn btn-primary">문제 등록</button>
    </div>
</form>
{%endblock contents%}
{%block javascript%}
<!--script src="/static/polls/js/script.js"-->
<script src='{% static "polls/js/script.js" %}'></script>
{%endblock javascript%}

mypoll_chat/polls/templates/polls/vote_form.html
{% extends "layout/main_layout.html" %}

{% block title%}설문하기{% endblock title%}
{% block contents%}
    <h1>설문 하기</h1>
    <h2>{{question.question_text}}</h2>

    {% if error_message %}
    <div style="color:red;font-size:0.9em">
        {{error_message}}
    </div>
    {% endif %}
    <!-- 보기 -->
    <form action="{% url 'polls:vote' %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="question_id" value="{{question.pk}}">
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" class="form-check-input"
                value="{{choice.pk}}" id="{{choice.pk}}">
            <label for="{{choice.pk}}">{{choice.choice_text}}</label><br>
        {% endfor %}
        <button type="submit" class="btn btn-primary">투표</button>
        <button type="reset" class="btn btn-primary">선택해제</button>
    </form>
{% endblock contents%}

mypoll_chat/polls/templates/polls/vote_result.html
{% extends "layout/main_layout.html"%}
{% block title %}설문 결과{% endblock title %}

{% block contents%}
<h1>설문 결과</h1>
<h2>{{question.pk}}. {{question.question_text}}</h2>
<ol>
    {% for choice in question.choice_set.all %}
        <li>{{choice.choice_text}} - {{choice.votes}}</li>
    {% endfor %}
</ol>
{% endblock contents%}

mypoll_chat/polls/templates/polls/welcome.html
<!-- polls/templates/polls/welcome.html -->
<!-- HTML이 아니라 django template  -->
{% extends "layout/main_layout.html"%}
{% load static %}
{% block title %}Home{% endblock title %}

{% block contents%}
<h1>Welcome-template</h1>
<p>
    <img src="/static/polls/imgs/survey.png">
    <img src="{% static 'polls/imgs/survey.png' %}">
</p>
<p>저희 설문 페이지를 방문해 주셔서 감사합니다.</p>
현재 시간: {{now}} <!--context value now를 출력-->

{% endblock contents%}