mypoll_chat/account/urls.py
# account/urls.py -> account app용 url conf

from django.urls import path
from . import views

app_name = "account"

urlpatterns = [
    path("create", views.create, name="create"),
    path("detail", views.detail, name='detail'),
    path("login", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path("update", views.update, name="update"),
    path("password_change", views.password_change, name="password_change"),
    path("delete", views.user_delete, name="delete"),
]

mypoll_chat/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.index, name='index'),
    path('stream/', views.stream_chat, name='stream_chat'),
]

mypoll_chat/config/urls.py
from django.contrib import admin
from django.urls import path, include
from polls import views
urlpatterns = [
    
    path("", views.welcome, name="welcome"),
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls")), 
    path("account/", include("account.urls")),
    path('chat/', include('chat.urls')),
]

mypoll_chat/polls/urls.py
# polls/urls.py
# polls app에 대한 url-view 매핑파일 (URL Conf)

# URLConf  - urlpatterns =[ 매핑 설정 ]
# 매핑 설정 - path("url경로", View, name="설정식별이름") 함수를 이용

from django.urls import path
from . import views   # 상대 경로로 import. `.` 현재 모듈이 있는 패키지.

app_name = "polls" # 전체 설정에 대한 prefix(namespace). 
                   # 설정 name에 공통적으로 앞에 붙일 이름 ("app_name:name")

urlpatterns = [
    path("welcome", views.welcome, name="welcome"),
    path("vote_list", views.list, name="list"), # polls/list -> polls/vote_list
    path("vote_form/<int:question_id>", views.vote_form, name="vote_form"),
    path("vote", views.vote, name="vote"),
    path("vote_result/<int:question_id>", views.vote_result, name="vote_result"),
    path("vote_create", views.vote_create, name="vote_create"),
    path("vote_delete/<int:question_id>", views.vote_delete, name="vote_delete"),
]


# polls/vote_form/<path파라미터값 타입:view의 파라미터변수명>
# <int:   #path parameter값을 int로 전달해라.
# <   :question_id> # view의 question_id 변수로 전달해라.
# type: int, str

mypoll_chat/templates/layout/main_layout.html
<!-- mypoll/templates/layout/main_layout.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}my poll{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/js/bootstrap.bundle.min.js" integrity="sha384-FKyoEForCGlyvwx9Hj09JcYn3nv7wiPVlz7YYwJrWVcXK/BmnVDxM+D2scQbITxI" crossorigin="anonymous"></script>
</head>
<body>
{# 메뉴바 추가 #}
<nav class="navbar navbar-expand-sm bg-success bg-opacity-10 mt-3">
    <div class="container">
        <!--
        로그인 해야 요청할 수 있는 메뉴: 설문등록, 자기정보조회, 로그아웃
        로그인 안한 사람만 요청할 수 있는 메뉴: 회원가입, 로그인
        로그인 관계없이 요청할 수 있는 메뉴: 설문목록
        -->
      
        <div class="navbar-nav">
            <a href="{% url 'polls:list' %}" class="nav-link">설문목록</a>

            {% if user.is_authenticated %}
                <a href="{% url 'polls:vote_create' %}" class="nav-link">설문등록</a>
                <a href="{% url 'account:detail' %}" class="nav-link">{{user.username}}</a>
                <a href="{% url 'account:logout' %}" class="nav-link">로그아웃</a>
            {% endif %}
            {% if not user.is_authenticated %}
                <a href="{% url 'account:create' %}" class="nav-link">회원가입</a>
                <a href="{% url 'account:login' %}" class="nav-link">로그인</a>
            {% endif %}
            <a href="{% url 'chat:index' %}" class="nav-link">챗봇</a>
            
        </div>
    </div>
</nav>
<div class="container mt-3">

{# block을 지정: 이 layout을 확장해서 구현할 페이지들이 내용을 넣을 영역. #}
{% block contents %}{% endblock contents%}
{% block javascript %}{% endblock javascript %}
</div>
</body>
</html>